# encoding: UTF-8
Vagrant.configure("2") do |config|

#speficy the base box
config.vm.box = "kaorimatz/ubuntu-16.04-amd64"
config.vm.network "private_network", type: "dhcp"
config.ssh.username = 'root'
vagrant ALL=(ALL) NOPASSWD:ALL 
config.ssh.insert_key = 'true'
config.vm.provision"shell" do |s|
	s.path="provision/set_hostname.sh"
	end

config.vm.provider "virtualbox" do |v|
v.name = "ansible.test"
	end
end