# encoding: UTF-8
Vagrant.configure("2") do |config|

#speficy the base box
config.vm.box = "kaorimatz/ubuntu-14.04.4-amd64"
config.vm.network "private_network", type: "dhcp"
	config.vm.provision"shell" do |s|
	s.path="provision/set_hostname.sh"
	end
config.ssh.insert_key = 'true'
config.vm.provider "virtualbox" do |v|
v.name = "ubuntu14.test"
	end
end